#ifndef C__USERS________RUFFLE_H_GENERATED_
#define C__USERS________RUFFLE_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'wbg' '__wbindgen_object_drop_ref' */
extern void (*Z_wbgZ___wbindgen_object_drop_refZ_vi)(u32);
/* import: 'wbg' '__wbindgen_cb_drop' */
extern u32 (*Z_wbgZ___wbindgen_cb_dropZ_ii)(u32);
/* import: 'wbg' '__wbindgen_string_new' */
extern u32 (*Z_wbgZ___wbindgen_string_newZ_iii)(u32, u32);
/* import: 'wbg' '__wbindgen_is_function' */
extern u32 (*Z_wbgZ___wbindgen_is_functionZ_ii)(u32);
/* import: 'wbg' '__wbindgen_json_parse' */
extern u32 (*Z_wbgZ___wbindgen_json_parseZ_iii)(u32, u32);
/* import: 'wbg' '__wbindgen_json_serialize' */
extern void (*Z_wbgZ___wbindgen_json_serializeZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_object_clone_ref' */
extern u32 (*Z_wbgZ___wbindgen_object_clone_refZ_ii)(u32);
/* import: 'wbg' '__wbg_isFullscreen_96b85640554e160d' */
extern u32 (*Z_wbgZ___wbg_isFullscreen_96b85640554e160dZ_ii)(u32);
/* import: 'wbg' '__wbg_displayUnsupportedMessage_a8f81a8e054e5e91' */
extern void (*Z_wbgZ___wbg_displayUnsupportedMessage_a8f81a8e054e5e91Z_vi)(u32);
/* import: 'wbg' '__wbg_displayMessage_c57c20204892da2b' */
extern void (*Z_wbgZ___wbg_displayMessage_c57c20204892da2bZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_new_df6e6ab7a65c4c4d' */
extern u32 (*Z_wbgZ___wbg_new_df6e6ab7a65c4c4dZ_iii)(u32, u32);
/* import: 'wbg' '__wbg_panic_bbc809dd04a12c60' */
extern void (*Z_wbgZ___wbg_panic_bbc809dd04a12c60Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_copyToAudioBuffer_58f244be94bac1d2' */
extern void (*Z_wbgZ___wbg_copyToAudioBuffer_58f244be94bac1d2Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_setMetadata_bbaeaee7f48274e6' */
extern void (*Z_wbgZ___wbg_setMetadata_bbaeaee7f48274e6Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_onCallbackAvailable_3a48fae397926c96' */
extern void (*Z_wbgZ___wbg_onCallbackAvailable_3a48fae397926c96Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_onFSCommand_fb2f94653f71796e' */
extern u32 (*Z_wbgZ___wbg_onFSCommand_fb2f94653f71796eZ_iiiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbindgen_number_new' */
extern u32 (*Z_wbgZ___wbindgen_number_newZ_id)(f64);
/* import: 'wbg' '__wbg_new_59cb74e423758ede' */
extern u32 (*Z_wbgZ___wbg_new_59cb74e423758edeZ_iv)(void);
/* import: 'wbg' '__wbg_stack_558ba5917b466edd' */
extern void (*Z_wbgZ___wbg_stack_558ba5917b466eddZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_error_4bb6c2a97407129a' */
extern void (*Z_wbgZ___wbg_error_4bb6c2a97407129aZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_is_undefined' */
extern u32 (*Z_wbgZ___wbindgen_is_undefinedZ_ii)(u32);
/* import: 'wbg' '__wbg_instanceof_WebGl2RenderingContext_61a66a1af6516586' */
extern u32 (*Z_wbgZ___wbg_instanceof_WebGl2RenderingContext_61a66a1af6516586Z_ii)(u32);
/* import: 'wbg' '__wbg_bindVertexArray_808c39d3c0f17264' */
extern void (*Z_wbgZ___wbg_bindVertexArray_808c39d3c0f17264Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_blitFramebuffer_3b625df19331f21c' */
extern void (*Z_wbgZ___wbg_blitFramebuffer_3b625df19331f21cZ_viiiiiiiiiii)(u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_createVertexArray_855d59250230c563' */
extern u32 (*Z_wbgZ___wbg_createVertexArray_855d59250230c563Z_ii)(u32);
/* import: 'wbg' '__wbg_renderbufferStorageMultisample_bbeb2b87cb14307f' */
extern void (*Z_wbgZ___wbg_renderbufferStorageMultisample_bbeb2b87cb14307fZ_viiiiii)(u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_texImage2D_173d216c50e54701' */
extern void (*Z_wbgZ___wbg_texImage2D_173d216c50e54701Z_viiiiiiiiiii)(u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_bindFramebuffer_ce3cfcfec4aa02cc' */
extern void (*Z_wbgZ___wbg_bindFramebuffer_ce3cfcfec4aa02ccZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_bindRenderbuffer_35f3639b7da4e4c7' */
extern void (*Z_wbgZ___wbg_bindRenderbuffer_35f3639b7da4e4c7Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_bindTexture_f2a0487a487a78d9' */
extern void (*Z_wbgZ___wbg_bindTexture_f2a0487a487a78d9Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_createFramebuffer_7fd863d54241be81' */
extern u32 (*Z_wbgZ___wbg_createFramebuffer_7fd863d54241be81Z_ii)(u32);
/* import: 'wbg' '__wbg_createRenderbuffer_52ebc0325ed6e885' */
extern u32 (*Z_wbgZ___wbg_createRenderbuffer_52ebc0325ed6e885Z_ii)(u32);
/* import: 'wbg' '__wbg_createTexture_a46f881a1c96b496' */
extern u32 (*Z_wbgZ___wbg_createTexture_a46f881a1c96b496Z_ii)(u32);
/* import: 'wbg' '__wbg_deleteFramebuffer_867aba8474910f62' */
extern void (*Z_wbgZ___wbg_deleteFramebuffer_867aba8474910f62Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_deleteRenderbuffer_eb162fd0beb632da' */
extern void (*Z_wbgZ___wbg_deleteRenderbuffer_eb162fd0beb632daZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_deleteTexture_1affe310edd12b75' */
extern void (*Z_wbgZ___wbg_deleteTexture_1affe310edd12b75Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_framebufferRenderbuffer_7bb033ee5a2eca8c' */
extern void (*Z_wbgZ___wbg_framebufferRenderbuffer_7bb033ee5a2eca8cZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_framebufferTexture2D_9a77a023fd4aedcc' */
extern void (*Z_wbgZ___wbg_framebufferTexture2D_9a77a023fd4aedccZ_viiiiii)(u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_getError_142acae679908a25' */
extern u32 (*Z_wbgZ___wbg_getError_142acae679908a25Z_ii)(u32);
/* import: 'wbg' '__wbg_getParameter_34e9af6606eb8544' */
extern u32 (*Z_wbgZ___wbg_getParameter_34e9af6606eb8544Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_texParameteri_e99b48aa90ae569b' */
extern void (*Z_wbgZ___wbg_texParameteri_e99b48aa90ae569bZ_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_instanceof_Window_9c4fd26090e1d029' */
extern u32 (*Z_wbgZ___wbg_instanceof_Window_9c4fd26090e1d029Z_ii)(u32);
/* import: 'wbg' '__wbg_document_249e9cf340780f93' */
extern u32 (*Z_wbgZ___wbg_document_249e9cf340780f93Z_ii)(u32);
/* import: 'wbg' '__wbg_location_cf542a8f458da7b4' */
extern u32 (*Z_wbgZ___wbg_location_cf542a8f458da7b4Z_ii)(u32);
/* import: 'wbg' '__wbg_navigator_fdf3521d0e190a9b' */
extern u32 (*Z_wbgZ___wbg_navigator_fdf3521d0e190a9bZ_ii)(u32);
/* import: 'wbg' '__wbg_devicePixelRatio_ea9c0157a379b3ec' */
extern f64 (*Z_wbgZ___wbg_devicePixelRatio_ea9c0157a379b3ecZ_di)(u32);
/* import: 'wbg' '__wbg_performance_e029cf47e1c47c09' */
extern u32 (*Z_wbgZ___wbg_performance_e029cf47e1c47c09Z_ii)(u32);
/* import: 'wbg' '__wbg_localStorage_884d77b5cedf820a' */
extern u32 (*Z_wbgZ___wbg_localStorage_884d77b5cedf820aZ_ii)(u32);
/* import: 'wbg' '__wbg_cancelAnimationFrame_28c6665c9b2a3944' */
extern void (*Z_wbgZ___wbg_cancelAnimationFrame_28c6665c9b2a3944Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_focus_b5729f61a3280cbc' */
extern void (*Z_wbgZ___wbg_focus_b5729f61a3280cbcZ_vi)(u32);
/* import: 'wbg' '__wbg_open_313f5801aab5e2f1' */
extern u32 (*Z_wbgZ___wbg_open_313f5801aab5e2f1Z_iiiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_requestAnimationFrame_aa3bab1f9557a4da' */
extern u32 (*Z_wbgZ___wbg_requestAnimationFrame_aa3bab1f9557a4daZ_iii)(u32, u32);
/* import: 'wbg' '__wbg_fetch_eaee025997e4cd56' */
extern u32 (*Z_wbgZ___wbg_fetch_eaee025997e4cd56Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_destination_c5ce4ac317c9219f' */
extern u32 (*Z_wbgZ___wbg_destination_c5ce4ac317c9219fZ_ii)(u32);
/* import: 'wbg' '__wbg_sampleRate_cc13fe55474678eb' */
extern f32 (*Z_wbgZ___wbg_sampleRate_cc13fe55474678ebZ_fi)(u32);
/* import: 'wbg' '__wbg_currentTime_ae061c195387b7ac' */
extern f64 (*Z_wbgZ___wbg_currentTime_ae061c195387b7acZ_di)(u32);
/* import: 'wbg' '__wbg_new_29e8884899ea6ee2' */
extern u32 (*Z_wbgZ___wbg_new_29e8884899ea6ee2Z_iv)(void);
/* import: 'wbg' '__wbg_suspend_4b5d3b7ee1f4a3ec' */
extern u32 (*Z_wbgZ___wbg_suspend_4b5d3b7ee1f4a3ecZ_ii)(u32);
/* import: 'wbg' '__wbg_createBuffer_53c7286e081d0b3e' */
extern u32 (*Z_wbgZ___wbg_createBuffer_53c7286e081d0b3eZ_iiiif)(u32, u32, u32, f32);
/* import: 'wbg' '__wbg_createBufferSource_8b7fd8bc4222b208' */
extern u32 (*Z_wbgZ___wbg_createBufferSource_8b7fd8bc4222b208Z_ii)(u32);
/* import: 'wbg' '__wbg_createChannelMerger_c059636adf34e09d' */
extern u32 (*Z_wbgZ___wbg_createChannelMerger_c059636adf34e09dZ_iii)(u32, u32);
/* import: 'wbg' '__wbg_createChannelSplitter_68062f62d4d66ed8' */
extern u32 (*Z_wbgZ___wbg_createChannelSplitter_68062f62d4d66ed8Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_createGain_7b6dadac3a6522d6' */
extern u32 (*Z_wbgZ___wbg_createGain_7b6dadac3a6522d6Z_ii)(u32);
/* import: 'wbg' '__wbg_createScriptProcessor_bce5438a51faa41d' */
extern u32 (*Z_wbgZ___wbg_createScriptProcessor_bce5438a51faa41dZ_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_decodeAudioData_81b31c0703465a21' */
extern u32 (*Z_wbgZ___wbg_decodeAudioData_81b31c0703465a21Z_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_resume_2c75f8fc1fd26d4b' */
extern u32 (*Z_wbgZ___wbg_resume_2c75f8fc1fd26d4bZ_ii)(u32);
/* import: 'wbg' '__wbg_gain_b3536e37256053f5' */
extern u32 (*Z_wbgZ___wbg_gain_b3536e37256053f5Z_ii)(u32);
/* import: 'wbg' '__wbg_protocol_2d293dcd35a07041' */
extern void (*Z_wbgZ___wbg_protocol_2d293dcd35a07041Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_assign_fc277322e1a88614' */
extern void (*Z_wbgZ___wbg_assign_fc277322e1a88614Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_baseURI_6a10de9fa3003a69' */
extern void (*Z_wbgZ___wbg_baseURI_6a10de9fa3003a69Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_appendChild_6ae001e6d3556190' */
extern u32 (*Z_wbgZ___wbg_appendChild_6ae001e6d3556190Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_setProperty_84c0a22125c731d6' */
extern void (*Z_wbgZ___wbg_setProperty_84c0a22125c731d6Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_new_3c2bf2a5257369ec' */
extern u32 (*Z_wbgZ___wbg_new_3c2bf2a5257369ecZ_iv)(void);
/* import: 'wbg' '__wbg_addPath_cf691ede06f38917' */
extern void (*Z_wbgZ___wbg_addPath_cf691ede06f38917Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_closePath_48f860f5bcbc79f3' */
extern void (*Z_wbgZ___wbg_closePath_48f860f5bcbc79f3Z_vi)(u32);
/* import: 'wbg' '__wbg_lineTo_7fd48462a80ac962' */
extern void (*Z_wbgZ___wbg_lineTo_7fd48462a80ac962Z_vidd)(u32, f64, f64);
/* import: 'wbg' '__wbg_moveTo_62ea44f899317925' */
extern void (*Z_wbgZ___wbg_moveTo_62ea44f899317925Z_vidd)(u32, f64, f64);
/* import: 'wbg' '__wbg_quadraticCurveTo_6f746087da5a242c' */
extern void (*Z_wbgZ___wbg_quadraticCurveTo_6f746087da5a242cZ_vidddd)(u32, f64, f64, f64, f64);
/* import: 'wbg' '__wbg_get_36b7a676e4c8aee9' */
extern void (*Z_wbgZ___wbg_get_36b7a676e4c8aee9Z_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_set_ad2026ce7b489f96' */
extern void (*Z_wbgZ___wbg_set_ad2026ce7b489f96Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_delete_9614de882c9a0cf5' */
extern void (*Z_wbgZ___wbg_delete_9614de882c9a0cf5Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_instanceof_SvgsvgElement_28ef05afde3449f9' */
extern u32 (*Z_wbgZ___wbg_instanceof_SvgsvgElement_28ef05afde3449f9Z_ii)(u32);
/* import: 'wbg' '__wbg_createSVGMatrix_43815bd5777c567f' */
extern u32 (*Z_wbgZ___wbg_createSVGMatrix_43815bd5777c567fZ_ii)(u32);
/* import: 'wbg' '__wbg_length_914ec377666a1fb8' */
extern u32 (*Z_wbgZ___wbg_length_914ec377666a1fb8Z_ii)(u32);
/* import: 'wbg' '__wbg_connect_3a117c24756fdf62' */
extern u32 (*Z_wbgZ___wbg_connect_3a117c24756fdf62Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_connect_3a51bca7e31cd323' */
extern u32 (*Z_wbgZ___wbg_connect_3a51bca7e31cd323Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_connect_52449bed6e387d23' */
extern u32 (*Z_wbgZ___wbg_connect_52449bed6e387d23Z_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_disconnect_b101656fb34b9fa3' */
extern void (*Z_wbgZ___wbg_disconnect_b101656fb34b9fa3Z_vi)(u32);
/* import: 'wbg' '__wbg_offsetX_951495e9516f0aeb' */
extern u32 (*Z_wbgZ___wbg_offsetX_951495e9516f0aebZ_ii)(u32);
/* import: 'wbg' '__wbg_offsetY_0377a1f53f902a1e' */
extern u32 (*Z_wbgZ___wbg_offsetY_0377a1f53f902a1eZ_ii)(u32);
/* import: 'wbg' '__wbg_button_c35922e0098b9cda' */
extern u32 (*Z_wbgZ___wbg_button_c35922e0098b9cdaZ_ii)(u32);
/* import: 'wbg' '__wbg_outputBuffer_7e7061041aa8a304' */
extern u32 (*Z_wbgZ___wbg_outputBuffer_7e7061041aa8a304Z_ii)(u32);
/* import: 'wbg' '__wbg_setTransform_4c6870c885e2b89e' */
extern void (*Z_wbgZ___wbg_setTransform_4c6870c885e2b89eZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_bindVertexArrayOES_bb8a104f35d5cf4f' */
extern void (*Z_wbgZ___wbg_bindVertexArrayOES_bb8a104f35d5cf4fZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_createVertexArrayOES_51a703442a9d8099' */
extern u32 (*Z_wbgZ___wbg_createVertexArrayOES_51a703442a9d8099Z_ii)(u32);
/* import: 'wbg' '__wbg_pointerId_e68d773decdc9224' */
extern u32 (*Z_wbgZ___wbg_pointerId_e68d773decdc9224Z_ii)(u32);
/* import: 'wbg' '__wbg_instanceof_Response_8295bf7aacde3233' */
extern u32 (*Z_wbgZ___wbg_instanceof_Response_8295bf7aacde3233Z_ii)(u32);
/* import: 'wbg' '__wbg_ok_e1e8f70fbf7c1fdc' */
extern u32 (*Z_wbgZ___wbg_ok_e1e8f70fbf7c1fdcZ_ii)(u32);
/* import: 'wbg' '__wbg_statusText_c5b7d9b4bc84d715' */
extern void (*Z_wbgZ___wbg_statusText_c5b7d9b4bc84d715Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_arrayBuffer_a98df6d58bb5ea26' */
extern u32 (*Z_wbgZ___wbg_arrayBuffer_a98df6d58bb5ea26Z_ii)(u32);
/* import: 'wbg' '__wbg_seta_5138c769bc027dee' */
extern void (*Z_wbgZ___wbg_seta_5138c769bc027deeZ_vif)(u32, f32);
/* import: 'wbg' '__wbg_setb_d92c5b9331343d2e' */
extern void (*Z_wbgZ___wbg_setb_d92c5b9331343d2eZ_vif)(u32, f32);
/* import: 'wbg' '__wbg_setc_c6fbbb68c7ba4693' */
extern void (*Z_wbgZ___wbg_setc_c6fbbb68c7ba4693Z_vif)(u32, f32);
/* import: 'wbg' '__wbg_setd_42dcf42c3ceabc9b' */
extern void (*Z_wbgZ___wbg_setd_42dcf42c3ceabc9bZ_vif)(u32, f32);
/* import: 'wbg' '__wbg_sete_49250c2d46b375b3' */
extern void (*Z_wbgZ___wbg_sete_49250c2d46b375b3Z_vif)(u32, f32);
/* import: 'wbg' '__wbg_setf_12cb2512fe19ba3f' */
extern void (*Z_wbgZ___wbg_setf_12cb2512fe19ba3fZ_vif)(u32, f32);
/* import: 'wbg' '__wbg_deltaY_49d792c5901e3fc1' */
extern f64 (*Z_wbgZ___wbg_deltaY_49d792c5901e3fc1Z_di)(u32);
/* import: 'wbg' '__wbg_deltaMode_7ed5ee895d112617' */
extern u32 (*Z_wbgZ___wbg_deltaMode_7ed5ee895d112617Z_ii)(u32);
/* import: 'wbg' '__wbg_setbuffer_5aca59a6f26d3307' */
extern void (*Z_wbgZ___wbg_setbuffer_5aca59a6f26d3307Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_setloop_710fa1431c2bc494' */
extern void (*Z_wbgZ___wbg_setloop_710fa1431c2bc494Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_setloopStart_988c5aad78cc446c' */
extern void (*Z_wbgZ___wbg_setloopStart_988c5aad78cc446cZ_vid)(u32, f64);
/* import: 'wbg' '__wbg_setloopEnd_fcc6c08574ca8ae5' */
extern void (*Z_wbgZ___wbg_setloopEnd_fcc6c08574ca8ae5Z_vid)(u32, f64);
/* import: 'wbg' '__wbg_setonended_0efd780b31d16bbf' */
extern void (*Z_wbgZ___wbg_setonended_0efd780b31d16bbfZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_start_e92060130d43d928' */
extern void (*Z_wbgZ___wbg_start_e92060130d43d928Z_vi)(u32);
/* import: 'wbg' '__wbg_start_a8d199336331f3a5' */
extern void (*Z_wbgZ___wbg_start_a8d199336331f3a5Z_vidd)(u32, f64, f64);
/* import: 'wbg' '__wbg_stop_37842cd5a56a341c' */
extern void (*Z_wbgZ___wbg_stop_37842cd5a56a341cZ_vid)(u32, f64);
/* import: 'wbg' '__wbg_instanceof_HtmlFormElement_de39c8070c818493' */
extern u32 (*Z_wbgZ___wbg_instanceof_HtmlFormElement_de39c8070c818493Z_ii)(u32);
/* import: 'wbg' '__wbg_submit_e668f2e6a4582aa6' */
extern void (*Z_wbgZ___wbg_submit_e668f2e6a4582aa6Z_vi)(u32);
/* import: 'wbg' '__wbg_now_4abbca4ef2aba8d6' */
extern f64 (*Z_wbgZ___wbg_now_4abbca4ef2aba8d6Z_di)(u32);
/* import: 'wbg' '__wbg_setonaudioprocess_9d6a213da205ae4d' */
extern void (*Z_wbgZ___wbg_setonaudioprocess_9d6a213da205ae4dZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_newwithbuffersourcesequenceandoptions_689c4999a01e0d8c' */
extern u32 (*Z_wbgZ___wbg_newwithbuffersourcesequenceandoptions_689c4999a01e0d8cZ_iii)(u32, u32);
/* import: 'wbg' '__wbg_addEventListener_b334b84e6525699c' */
extern void (*Z_wbgZ___wbg_addEventListener_b334b84e6525699cZ_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_addEventListener_502683a26945b1a5' */
extern void (*Z_wbgZ___wbg_addEventListener_502683a26945b1a5Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_addEventListener_b88d8dd107ce2f39' */
extern void (*Z_wbgZ___wbg_addEventListener_b88d8dd107ce2f39Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_removeEventListener_380d0ebdf9cd12ba' */
extern void (*Z_wbgZ___wbg_removeEventListener_380d0ebdf9cd12baZ_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_removeEventListener_1f30d3e3ef4ee58e' */
extern void (*Z_wbgZ___wbg_removeEventListener_1f30d3e3ef4ee58eZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_instanceof_HtmlCanvasElement_e0e251da2aa0b541' */
extern u32 (*Z_wbgZ___wbg_instanceof_HtmlCanvasElement_e0e251da2aa0b541Z_ii)(u32);
/* import: 'wbg' '__wbg_width_5843e31ec081f978' */
extern u32 (*Z_wbgZ___wbg_width_5843e31ec081f978Z_ii)(u32);
/* import: 'wbg' '__wbg_setwidth_fd251e9da5abcced' */
extern void (*Z_wbgZ___wbg_setwidth_fd251e9da5abccedZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_height_872c06b1bc666dd9' */
extern u32 (*Z_wbgZ___wbg_height_872c06b1bc666dd9Z_ii)(u32);
/* import: 'wbg' '__wbg_setheight_5b882973e84fa13c' */
extern void (*Z_wbgZ___wbg_setheight_5b882973e84fa13cZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_getContext_d778ffc8203f64ae' */
extern u32 (*Z_wbgZ___wbg_getContext_d778ffc8203f64aeZ_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_getContext_4678c25f580222b0' */
extern u32 (*Z_wbgZ___wbg_getContext_4678c25f580222b0Z_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_data_7db9e348ce1855fa' */
extern void (*Z_wbgZ___wbg_data_7db9e348ce1855faZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_key_97a48109ce6890c4' */
extern void (*Z_wbgZ___wbg_key_97a48109ce6890c4Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_code_e70e2272901f086c' */
extern void (*Z_wbgZ___wbg_code_e70e2272901f086cZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_body_0d97f334de622953' */
extern u32 (*Z_wbgZ___wbg_body_0d97f334de622953Z_ii)(u32);
/* import: 'wbg' '__wbg_createElement_ba61aad8af6be7f4' */
extern u32 (*Z_wbgZ___wbg_createElement_ba61aad8af6be7f4Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_createElementNS_c951238dc260501e' */
extern u32 (*Z_wbgZ___wbg_createElementNS_c951238dc260501eZ_iiiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_setid_16518c90432c2f8e' */
extern void (*Z_wbgZ___wbg_setid_16518c90432c2f8eZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_clientWidth_405142b36824cd4f' */
extern u32 (*Z_wbgZ___wbg_clientWidth_405142b36824cd4fZ_ii)(u32);
/* import: 'wbg' '__wbg_clientHeight_645231c9da3480a9' */
extern u32 (*Z_wbgZ___wbg_clientHeight_645231c9da3480a9Z_ii)(u32);
/* import: 'wbg' '__wbg_querySelector_6c8f27227fc14315' */
extern u32 (*Z_wbgZ___wbg_querySelector_6c8f27227fc14315Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_releasePointerCapture_758b760808d6ce02' */
extern void (*Z_wbgZ___wbg_releasePointerCapture_758b760808d6ce02Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_setAttribute_0b50656f1ccc45bf' */
extern void (*Z_wbgZ___wbg_setAttribute_0b50656f1ccc45bfZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_setAttributeNS_d31649e78e2cf95c' */
extern void (*Z_wbgZ___wbg_setAttributeNS_d31649e78e2cf95cZ_viiiiiii)(u32, u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_setPointerCapture_6f31425163cf44a1' */
extern void (*Z_wbgZ___wbg_setPointerCapture_6f31425163cf44a1Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_remove_eabff3d9e444a826' */
extern void (*Z_wbgZ___wbg_remove_eabff3d9e444a826Z_vi)(u32);
/* import: 'wbg' '__wbg_instanceof_WebGlRenderingContext_5671fd2c102046b1' */
extern u32 (*Z_wbgZ___wbg_instanceof_WebGlRenderingContext_5671fd2c102046b1Z_ii)(u32);
/* import: 'wbg' '__wbg_drawingBufferWidth_0f8ef2b95bb66c81' */
extern u32 (*Z_wbgZ___wbg_drawingBufferWidth_0f8ef2b95bb66c81Z_ii)(u32);
/* import: 'wbg' '__wbg_drawingBufferHeight_04a3507b6fb21bac' */
extern u32 (*Z_wbgZ___wbg_drawingBufferHeight_04a3507b6fb21bacZ_ii)(u32);
/* import: 'wbg' '__wbg_bufferData_9f09145baa3273f9' */
extern void (*Z_wbgZ___wbg_bufferData_9f09145baa3273f9Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_texImage2D_48722cf9f95c8df8' */
extern void (*Z_wbgZ___wbg_texImage2D_48722cf9f95c8df8Z_viiiiiiiiiii)(u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_uniform1fv_0b5950d4f588ac7e' */
extern void (*Z_wbgZ___wbg_uniform1fv_0b5950d4f588ac7eZ_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_uniform4fv_8fa4c0052d79aed2' */
extern void (*Z_wbgZ___wbg_uniform4fv_8fa4c0052d79aed2Z_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_uniformMatrix3fv_c4a15deb8d8fbd61' */
extern void (*Z_wbgZ___wbg_uniformMatrix3fv_c4a15deb8d8fbd61Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_uniformMatrix4fv_62951f66fbf764cd' */
extern void (*Z_wbgZ___wbg_uniformMatrix4fv_62951f66fbf764cdZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_activeTexture_790fa161eaf8dcb0' */
extern void (*Z_wbgZ___wbg_activeTexture_790fa161eaf8dcb0Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_attachShader_5446231928034874' */
extern void (*Z_wbgZ___wbg_attachShader_5446231928034874Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_bindBuffer_5b0bd39cdc9f3c91' */
extern void (*Z_wbgZ___wbg_bindBuffer_5b0bd39cdc9f3c91Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_bindFramebuffer_9490ff183a431d0d' */
extern void (*Z_wbgZ___wbg_bindFramebuffer_9490ff183a431d0dZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_bindRenderbuffer_86495e658e23020f' */
extern void (*Z_wbgZ___wbg_bindRenderbuffer_86495e658e23020fZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_bindTexture_6df7d2262019c813' */
extern void (*Z_wbgZ___wbg_bindTexture_6df7d2262019c813Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_blendFunc_c91f929b64e24ca6' */
extern void (*Z_wbgZ___wbg_blendFunc_c91f929b64e24ca6Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_clear_216e95e64c0ce688' */
extern void (*Z_wbgZ___wbg_clear_216e95e64c0ce688Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_clearColor_f7316ccd75b2a3b1' */
extern void (*Z_wbgZ___wbg_clearColor_f7316ccd75b2a3b1Z_viffff)(u32, f32, f32, f32, f32);
/* import: 'wbg' '__wbg_colorMask_cc8730de91ea02ce' */
extern void (*Z_wbgZ___wbg_colorMask_cc8730de91ea02ceZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_compileShader_749eb91c541c360c' */
extern void (*Z_wbgZ___wbg_compileShader_749eb91c541c360cZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_createBuffer_8ae1735de737ca21' */
extern u32 (*Z_wbgZ___wbg_createBuffer_8ae1735de737ca21Z_ii)(u32);
/* import: 'wbg' '__wbg_createProgram_28f1378728397a46' */
extern u32 (*Z_wbgZ___wbg_createProgram_28f1378728397a46Z_ii)(u32);
/* import: 'wbg' '__wbg_createShader_f6da8384be38c095' */
extern u32 (*Z_wbgZ___wbg_createShader_f6da8384be38c095Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_createTexture_be549d53d11ebf83' */
extern u32 (*Z_wbgZ___wbg_createTexture_be549d53d11ebf83Z_ii)(u32);
/* import: 'wbg' '__wbg_disable_b2672dfd98db0d2c' */
extern void (*Z_wbgZ___wbg_disable_b2672dfd98db0d2cZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_disableVertexAttribArray_f5154961c6bbc61f' */
extern void (*Z_wbgZ___wbg_disableVertexAttribArray_f5154961c6bbc61fZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_drawElements_19a4ea67a2f14d44' */
extern void (*Z_wbgZ___wbg_drawElements_19a4ea67a2f14d44Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_enable_9c5b69ae0579565d' */
extern void (*Z_wbgZ___wbg_enable_9c5b69ae0579565dZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_enableVertexAttribArray_eff1f71734ec0c24' */
extern void (*Z_wbgZ___wbg_enableVertexAttribArray_eff1f71734ec0c24Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_getAttribLocation_7321b82ba20f42ed' */
extern u32 (*Z_wbgZ___wbg_getAttribLocation_7321b82ba20f42edZ_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_getExtension_29e749f65dd345b5' */
extern u32 (*Z_wbgZ___wbg_getExtension_29e749f65dd345b5Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_getParameter_e02390c31b2aedb9' */
extern u32 (*Z_wbgZ___wbg_getParameter_e02390c31b2aedb9Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_getProgramInfoLog_89c655cf7d3deb29' */
extern void (*Z_wbgZ___wbg_getProgramInfoLog_89c655cf7d3deb29Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_getProgramParameter_97fb617622a1e9c6' */
extern u32 (*Z_wbgZ___wbg_getProgramParameter_97fb617622a1e9c6Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_getShaderInfoLog_8fbfc8052cd2a5c2' */
extern void (*Z_wbgZ___wbg_getShaderInfoLog_8fbfc8052cd2a5c2Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_getUniformLocation_8ef86decd2ceb6a0' */
extern u32 (*Z_wbgZ___wbg_getUniformLocation_8ef86decd2ceb6a0Z_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_linkProgram_b060b6f5c6419695' */
extern void (*Z_wbgZ___wbg_linkProgram_b060b6f5c6419695Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_pixelStorei_1e9534b41710bd3f' */
extern void (*Z_wbgZ___wbg_pixelStorei_1e9534b41710bd3fZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_shaderSource_e00c8c2b41679a01' */
extern void (*Z_wbgZ___wbg_shaderSource_e00c8c2b41679a01Z_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_stencilFunc_eeb2374a49160e1e' */
extern void (*Z_wbgZ___wbg_stencilFunc_eeb2374a49160e1eZ_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_stencilMask_8383787c8968e634' */
extern void (*Z_wbgZ___wbg_stencilMask_8383787c8968e634Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_stencilOp_d618117604d44e35' */
extern void (*Z_wbgZ___wbg_stencilOp_d618117604d44e35Z_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_texParameteri_58c0d4e82f062e6f' */
extern void (*Z_wbgZ___wbg_texParameteri_58c0d4e82f062e6fZ_viiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_uniform1f_affc2490c2cff524' */
extern void (*Z_wbgZ___wbg_uniform1f_affc2490c2cff524Z_viif)(u32, u32, f32);
/* import: 'wbg' '__wbg_uniform1i_584ce89a2fa7078d' */
extern void (*Z_wbgZ___wbg_uniform1i_584ce89a2fa7078dZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_useProgram_ad5593b87b2aec4f' */
extern void (*Z_wbgZ___wbg_useProgram_ad5593b87b2aec4fZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_vertexAttribPointer_3e272f16a22bb68c' */
extern void (*Z_wbgZ___wbg_vertexAttribPointer_3e272f16a22bb68cZ_viiiiiii)(u32, u32, u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_viewport_40ac6422fa7e7109' */
extern void (*Z_wbgZ___wbg_viewport_40ac6422fa7e7109Z_viiiii)(u32, u32, u32, u32, u32);
/* import: 'wbg' '__wbg_debug_3c0b82934d1dd91e' */
extern void (*Z_wbgZ___wbg_debug_3c0b82934d1dd91eZ_vi)(u32);
/* import: 'wbg' '__wbg_error_9ff84d33a850b1ef' */
extern void (*Z_wbgZ___wbg_error_9ff84d33a850b1efZ_vi)(u32);
/* import: 'wbg' '__wbg_info_3b2058a219fa31b9' */
extern void (*Z_wbgZ___wbg_info_3b2058a219fa31b9Z_vi)(u32);
/* import: 'wbg' '__wbg_log_386a8115a84a780d' */
extern void (*Z_wbgZ___wbg_log_386a8115a84a780dZ_vi)(u32);
/* import: 'wbg' '__wbg_warn_5fc232d538408d4a' */
extern void (*Z_wbgZ___wbg_warn_5fc232d538408d4aZ_vi)(u32);
/* import: 'wbg' '__wbg_style_9290c51fe7cb7783' */
extern u32 (*Z_wbgZ___wbg_style_9290c51fe7cb7783Z_ii)(u32);
/* import: 'wbg' '__wbg_setvalue_e8ff05630a7ffecb' */
extern void (*Z_wbgZ___wbg_setvalue_e8ff05630a7ffecbZ_vif)(u32, f32);
/* import: 'wbg' '__wbg_linearRampToValueAtTime_0245aa9e5d87776f' */
extern u32 (*Z_wbgZ___wbg_linearRampToValueAtTime_0245aa9e5d87776fZ_iifd)(u32, f32, f64);
/* import: 'wbg' '__wbg_setValueAtTime_b4a172acdfc9830f' */
extern u32 (*Z_wbgZ___wbg_setValueAtTime_b4a172acdfc9830fZ_iifd)(u32, f32, f64);
/* import: 'wbg' '__wbg_currentTarget_a3b06d00ff76859b' */
extern u32 (*Z_wbgZ___wbg_currentTarget_a3b06d00ff76859bZ_ii)(u32);
/* import: 'wbg' '__wbg_preventDefault_19876bf3a4179b34' */
extern void (*Z_wbgZ___wbg_preventDefault_19876bf3a4179b34Z_vi)(u32);
/* import: 'wbg' '__wbg_setsrc_21ed0b40d0ff0413' */
extern void (*Z_wbgZ___wbg_setsrc_21ed0b40d0ff0413Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_new_0891fac076d9e6b3' */
extern u32 (*Z_wbgZ___wbg_new_0891fac076d9e6b3Z_iv)(void);
/* import: 'wbg' '__wbg_newwithwidthandheight_045e54743ae79290' */
extern u32 (*Z_wbgZ___wbg_newwithwidthandheight_045e54743ae79290Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_userAgent_89e0d93ea0bfe354' */
extern void (*Z_wbgZ___wbg_userAgent_89e0d93ea0bfe354Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_newwithstrandinit_a58924208f457f33' */
extern u32 (*Z_wbgZ___wbg_newwithstrandinit_a58924208f457f33Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_instanceof_CanvasRenderingContext2d_eea9cd931eb496b7' */
extern u32 (*Z_wbgZ___wbg_instanceof_CanvasRenderingContext2d_eea9cd931eb496b7Z_ii)(u32);
/* import: 'wbg' '__wbg_setglobalAlpha_6b6fb9a57a09df9d' */
extern void (*Z_wbgZ___wbg_setglobalAlpha_6b6fb9a57a09df9dZ_vid)(u32, f64);
/* import: 'wbg' '__wbg_setglobalCompositeOperation_e404daf7e6bb63e4' */
extern void (*Z_wbgZ___wbg_setglobalCompositeOperation_e404daf7e6bb63e4Z_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_setstrokeStyle_72f1ad8117744d41' */
extern void (*Z_wbgZ___wbg_setstrokeStyle_72f1ad8117744d41Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_setfillStyle_5306396b0368ba08' */
extern void (*Z_wbgZ___wbg_setfillStyle_5306396b0368ba08Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_setfilter_fa947e793349a2de' */
extern void (*Z_wbgZ___wbg_setfilter_fa947e793349a2deZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_setlineWidth_9f25e0ceca65a4d7' */
extern void (*Z_wbgZ___wbg_setlineWidth_9f25e0ceca65a4d7Z_vid)(u32, f64);
/* import: 'wbg' '__wbg_setlineCap_6c7169ac07a6349e' */
extern void (*Z_wbgZ___wbg_setlineCap_6c7169ac07a6349eZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_setlineJoin_d6311997533dcdbf' */
extern void (*Z_wbgZ___wbg_setlineJoin_d6311997533dcdbfZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_setmiterLimit_cd181ac4dc64fc1d' */
extern void (*Z_wbgZ___wbg_setmiterLimit_cd181ac4dc64fc1dZ_vid)(u32, f64);
/* import: 'wbg' '__wbg_drawImage_ff0075aa41bc6155' */
extern void (*Z_wbgZ___wbg_drawImage_ff0075aa41bc6155Z_viidd)(u32, u32, f64, f64);
/* import: 'wbg' '__wbg_drawImage_b43cf9d292491493' */
extern void (*Z_wbgZ___wbg_drawImage_b43cf9d292491493Z_viidd)(u32, u32, f64, f64);
/* import: 'wbg' '__wbg_fill_a928208ebdb3fecc' */
extern void (*Z_wbgZ___wbg_fill_a928208ebdb3feccZ_vii)(u32, u32);
/* import: 'wbg' '__wbg_stroke_c19677a93050ef02' */
extern void (*Z_wbgZ___wbg_stroke_c19677a93050ef02Z_vii)(u32, u32);
/* import: 'wbg' '__wbg_createPattern_a737181b452c0941' */
extern u32 (*Z_wbgZ___wbg_createPattern_a737181b452c0941Z_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_getImageData_6e56dc172cd2ed36' */
extern u32 (*Z_wbgZ___wbg_getImageData_6e56dc172cd2ed36Z_iidddd)(u32, f64, f64, f64, f64);
/* import: 'wbg' '__wbg_clearRect_dbb56982eff2a250' */
extern void (*Z_wbgZ___wbg_clearRect_dbb56982eff2a250Z_vidddd)(u32, f64, f64, f64, f64);
/* import: 'wbg' '__wbg_fillRect_33b210367d4a0063' */
extern void (*Z_wbgZ___wbg_fillRect_33b210367d4a0063Z_vidddd)(u32, f64, f64, f64, f64);
/* import: 'wbg' '__wbg_resetTransform_09cd4a47a1d0fc9c' */
extern void (*Z_wbgZ___wbg_resetTransform_09cd4a47a1d0fc9cZ_vi)(u32);
/* import: 'wbg' '__wbg_setTransform_36254c0c8f264eee' */
extern void (*Z_wbgZ___wbg_setTransform_36254c0c8f264eeeZ_vidddddd)(u32, f64, f64, f64, f64, f64, f64);
/* import: 'wbg' '__wbg_get_f099d98ea7d68360' */
extern u32 (*Z_wbgZ___wbg_get_f099d98ea7d68360Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_next_9d10ccb28a5fd327' */
extern u32 (*Z_wbgZ___wbg_next_9d10ccb28a5fd327Z_ii)(u32);
/* import: 'wbg' '__wbg_done_faa42c8d1dd8ca9e' */
extern u32 (*Z_wbgZ___wbg_done_faa42c8d1dd8ca9eZ_ii)(u32);
/* import: 'wbg' '__wbg_value_9befa7ab4a7326bf' */
extern u32 (*Z_wbgZ___wbg_value_9befa7ab4a7326bfZ_ii)(u32);
/* import: 'wbg' '__wbg_get_0c6963cbab34fbb6' */
extern u32 (*Z_wbgZ___wbg_get_0c6963cbab34fbb6Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_call_cb478d88f3068c91' */
extern u32 (*Z_wbgZ___wbg_call_cb478d88f3068c91Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_new_8528c110a833413f' */
extern u32 (*Z_wbgZ___wbg_new_8528c110a833413fZ_iv)(void);
/* import: 'wbg' '__wbg_isArray_bccef1135dd559c1' */
extern u32 (*Z_wbgZ___wbg_isArray_bccef1135dd559c1Z_ii)(u32);
/* import: 'wbg' '__wbg_of_1988d238bc84b807' */
extern u32 (*Z_wbgZ___wbg_of_1988d238bc84b807Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_push_17a514d8ab666103' */
extern u32 (*Z_wbgZ___wbg_push_17a514d8ab666103Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_instanceof_ArrayBuffer_ee6a79eaea0f4f5b' */
extern u32 (*Z_wbgZ___wbg_instanceof_ArrayBuffer_ee6a79eaea0f4f5bZ_ii)(u32);
/* import: 'wbg' '__wbg_new_66923a754de9cf28' */
extern u32 (*Z_wbgZ___wbg_new_66923a754de9cf28Z_ii)(u32);
/* import: 'wbg' '__wbg_slice_1b99bf7e559f62b2' */
extern u32 (*Z_wbgZ___wbg_slice_1b99bf7e559f62b2Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_values_0e37ea0767d5caba' */
extern u32 (*Z_wbgZ___wbg_values_0e37ea0767d5cabaZ_ii)(u32);
/* import: 'wbg' '__wbg_newnoargs_3efc7bfa69a681f9' */
extern u32 (*Z_wbgZ___wbg_newnoargs_3efc7bfa69a681f9Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_apply_2d67e7379df5344f' */
extern u32 (*Z_wbgZ___wbg_apply_2d67e7379df5344fZ_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_call_f5e0576f61ee7461' */
extern u32 (*Z_wbgZ___wbg_call_f5e0576f61ee7461Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_getTime_135e6afc6013ba72' */
extern f64 (*Z_wbgZ___wbg_getTime_135e6afc6013ba72Z_di)(u32);
/* import: 'wbg' '__wbg_getTimezoneOffset_39fb6af112fac02f' */
extern f64 (*Z_wbgZ___wbg_getTimezoneOffset_39fb6af112fac02fZ_di)(u32);
/* import: 'wbg' '__wbg_new0_8e8ab0e7714cf1dd' */
extern u32 (*Z_wbgZ___wbg_new0_8e8ab0e7714cf1ddZ_iv)(void);
/* import: 'wbg' '__wbg_instanceof_Object_d6b4e933180fbb26' */
extern u32 (*Z_wbgZ___wbg_instanceof_Object_d6b4e933180fbb26Z_ii)(u32);
/* import: 'wbg' '__wbg_entries_a9881e0ca10e3cb2' */
extern u32 (*Z_wbgZ___wbg_entries_a9881e0ca10e3cb2Z_ii)(u32);
/* import: 'wbg' '__wbg_fromEntries_8be754b4532b35f4' */
extern u32 (*Z_wbgZ___wbg_fromEntries_8be754b4532b35f4Z_ii)(u32);
/* import: 'wbg' '__wbg_is_573b30cf06a763fb' */
extern u32 (*Z_wbgZ___wbg_is_573b30cf06a763fbZ_iii)(u32, u32);
/* import: 'wbg' '__wbg_new_d14bf16e62c6b3d5' */
extern u32 (*Z_wbgZ___wbg_new_d14bf16e62c6b3d5Z_iv)(void);
/* import: 'wbg' '__wbg_resolve_778af3f90b8e2b59' */
extern u32 (*Z_wbgZ___wbg_resolve_778af3f90b8e2b59Z_ii)(u32);
/* import: 'wbg' '__wbg_then_367b3e718069cfb9' */
extern u32 (*Z_wbgZ___wbg_then_367b3e718069cfb9Z_iii)(u32, u32);
/* import: 'wbg' '__wbg_then_ac66ca61394bfd21' */
extern u32 (*Z_wbgZ___wbg_then_ac66ca61394bfd21Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_self_05c54dcacb623b9a' */
extern u32 (*Z_wbgZ___wbg_self_05c54dcacb623b9aZ_iv)(void);
/* import: 'wbg' '__wbg_window_9777ce446d12989f' */
extern u32 (*Z_wbgZ___wbg_window_9777ce446d12989fZ_iv)(void);
/* import: 'wbg' '__wbg_globalThis_f0ca0bbb0149cf3d' */
extern u32 (*Z_wbgZ___wbg_globalThis_f0ca0bbb0149cf3dZ_iv)(void);
/* import: 'wbg' '__wbg_global_c3c8325ae8c7f1a9' */
extern u32 (*Z_wbgZ___wbg_global_c3c8325ae8c7f1a9Z_iv)(void);
/* import: 'wbg' '__wbg_buffer_ebc6c8e75510eae3' */
extern u32 (*Z_wbgZ___wbg_buffer_ebc6c8e75510eae3Z_ii)(u32);
/* import: 'wbg' '__wbg_newwithbyteoffsetandlength_ca3d3d8811ecb569' */
extern u32 (*Z_wbgZ___wbg_newwithbyteoffsetandlength_ca3d3d8811ecb569Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbg_length_317f0dd77f7a6673' */
extern u32 (*Z_wbgZ___wbg_length_317f0dd77f7a6673Z_ii)(u32);
/* import: 'wbg' '__wbg_new_135e963dedf67b22' */
extern u32 (*Z_wbgZ___wbg_new_135e963dedf67b22Z_ii)(u32);
/* import: 'wbg' '__wbg_set_4a5072a31008e0cb' */
extern void (*Z_wbgZ___wbg_set_4a5072a31008e0cbZ_viii)(u32, u32, u32);
/* import: 'wbg' '__wbg_fill_f08a873179c69e31' */
extern u32 (*Z_wbgZ___wbg_fill_f08a873179c69e31Z_iiiii)(u32, u32, u32, u32);
/* import: 'wbg' '__wbg_buffer_3580452571655bd0' */
extern u32 (*Z_wbgZ___wbg_buffer_3580452571655bd0Z_ii)(u32);
/* import: 'wbg' '__wbg_byteLength_7d55aca7ec6c42cb' */
extern u32 (*Z_wbgZ___wbg_byteLength_7d55aca7ec6c42cbZ_ii)(u32);
/* import: 'wbg' '__wbg_byteOffset_2ebe3f5c421f3a99' */
extern u32 (*Z_wbgZ___wbg_byteOffset_2ebe3f5c421f3a99Z_ii)(u32);
/* import: 'wbg' '__wbg_ownKeys_b6c8becb6576203e' */
extern u32 (*Z_wbgZ___wbg_ownKeys_b6c8becb6576203eZ_ii)(u32);
/* import: 'wbg' '__wbg_set_61642586f7156f4a' */
extern u32 (*Z_wbgZ___wbg_set_61642586f7156f4aZ_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_number_get' */
extern void (*Z_wbgZ___wbindgen_number_getZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_string_get' */
extern void (*Z_wbgZ___wbindgen_string_getZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_boolean_get' */
extern u32 (*Z_wbgZ___wbindgen_boolean_getZ_ii)(u32);
/* import: 'wbg' '__wbindgen_debug_string' */
extern void (*Z_wbgZ___wbindgen_debug_stringZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_throw' */
extern void (*Z_wbgZ___wbindgen_throwZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_rethrow' */
extern void (*Z_wbgZ___wbindgen_rethrowZ_vi)(u32);
/* import: 'wbg' '__wbindgen_memory' */
extern u32 (*Z_wbgZ___wbindgen_memoryZ_iv)(void);
/* import: 'wbg' '__wbindgen_closure_wrapper398' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper398Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper400' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper400Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper402' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper402Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper404' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper404Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper406' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper406Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper408' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper408Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper410' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper410Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper412' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper412Z_iiii)(u32, u32, u32);
/* import: 'wbg' '__wbindgen_closure_wrapper1753' */
extern u32 (*Z_wbgZ___wbindgen_closure_wrapper1753Z_iiii)(u32, u32, u32);

/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: '__wbg_ruffle_free' */
extern void (*WASM_RT_ADD_PREFIX(Z___wbg_ruffle_freeZ_vi))(u32);
/* export: 'ruffle_new' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_ruffle_newZ_iiii))(u32, u32, u32);
/* export: 'ruffle_stream_from' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_stream_fromZ_viiii))(u32, u32, u32, u32);
/* export: 'ruffle_load_data' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_load_dataZ_viii))(u32, u32, u32);
/* export: 'ruffle_play' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_playZ_vi))(u32);
/* export: 'ruffle_pause' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_pauseZ_vi))(u32);
/* export: 'ruffle_is_playing' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_ruffle_is_playingZ_ii))(u32);
/* export: 'ruffle_prepare_context_menu' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_ruffle_prepare_context_menuZ_ii))(u32);
/* export: 'ruffle_run_context_menu_callback' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_run_context_menu_callbackZ_vii))(u32, u32);
/* export: 'ruffle_clear_custom_menu_items' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_clear_custom_menu_itemsZ_vi))(u32);
/* export: 'ruffle_destroy' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_destroyZ_vi))(u32);
/* export: 'ruffle_call_exposed_callback' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_ruffle_call_exposed_callbackZ_iiiiii))(u32, u32, u32, u32, u32);
/* export: 'ruffle_set_trace_observer' */
extern void (*WASM_RT_ADD_PREFIX(Z_ruffle_set_trace_observerZ_vii))(u32, u32);
/* export: 'ruffle_audio_context' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_ruffle_audio_contextZ_ii))(u32);
/* export: '__wbindgen_malloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_mallocZ_ii))(u32);
/* export: '__wbindgen_realloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_reallocZ_iiii))(u32, u32, u32);
/* export: '__wbindgen_export_2' */
extern wasm_rt_table_t (*WASM_RT_ADD_PREFIX(Z___wbindgen_export_2));
/* export: '_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0172ae82e3c2ecf2' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0172ae82e3c2ecf2Z_viii))(u32, u32, u32);
/* export: '_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3703e8cc5c3423ff' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3703e8cc5c3423ffZ_viid))(u32, u32, f64);
/* export: '_dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2d1db5206beeca55' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2d1db5206beeca55Z_vii))(u32, u32);
/* export: '_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h8d67278ba0bc03f4' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h8d67278ba0bc03f4Z_viii))(u32, u32, u32);
/* export: '__wbindgen_exn_store' */
extern void (*WASM_RT_ADD_PREFIX(Z___wbindgen_exn_storeZ_vi))(u32);
/* export: '__wbindgen_free' */
extern void (*WASM_RT_ADD_PREFIX(Z___wbindgen_freeZ_vii))(u32, u32);
#ifdef __cplusplus
}
#endif

#endif  /* C__USERS________RUFFLE_H_GENERATED_ */
