name: Compile

on:
  # Allow for manual dispatch on GitHub
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          platform: i686
        
      - name: compile
        run: |
            clang -O3 --target=i686-pc-windows-msvc -shared -o ./ruffle.dll ruffle.c

      - name: Upload artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./ruffle.dll
          name: ruffle.dll
